syntax = "proto3";
package mmo;
option java_package = "com.mmo.grpc";
option java_outer_classname = "GameBridgeProto";

message EntityState {
    string id = 1;
    string character = 2;
    float x = 3;
    float y = 4;
    string action = 5;
    bool isFacingLeft = 6;
}

message GameWorldUpdate {
    repeated EntityState players = 1;
    EntityState boss = 2;
    repeated EntityState enemies = 3; // NEW: Dedicated enemy stream!
}

message GameState {
    string player_id = 1;
    float player_x = 2;
    float player_y = 3;
    string action = 4;
}

message BotScript {
    string bot_id = 1;
    string generated_command = 2;
}

service AIEngine {
    rpc JoinLobby(stream EntityState) returns (stream GameWorldUpdate);
    rpc SendState(GameState) returns (BotScript);
}