# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_bridge_pb2 as game__bridge__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIEngineStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinLobby = channel.stream_stream(
                '/mmo.AIEngine/JoinLobby',
                request_serializer=game__bridge__pb2.EntityState.SerializeToString,
                response_deserializer=game__bridge__pb2.GameWorldUpdate.FromString,
                _registered_method=True)
        self.SendState = channel.unary_unary(
                '/mmo.AIEngine/SendState',
                request_serializer=game__bridge__pb2.GameState.SerializeToString,
                response_deserializer=game__bridge__pb2.BotScript.FromString,
                _registered_method=True)


class AIEngineServicer:
    """Missing associated documentation comment in .proto file."""

    def JoinLobby(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinLobby': grpc.stream_stream_rpc_method_handler(
                    servicer.JoinLobby,
                    request_deserializer=game__bridge__pb2.EntityState.FromString,
                    response_serializer=game__bridge__pb2.GameWorldUpdate.SerializeToString,
            ),
            'SendState': grpc.unary_unary_rpc_method_handler(
                    servicer.SendState,
                    request_deserializer=game__bridge__pb2.GameState.FromString,
                    response_serializer=game__bridge__pb2.BotScript.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmo.AIEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mmo.AIEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIEngine:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinLobby(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mmo.AIEngine/JoinLobby',
            game__bridge__pb2.EntityState.SerializeToString,
            game__bridge__pb2.GameWorldUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmo.AIEngine/SendState',
            game__bridge__pb2.GameState.SerializeToString,
            game__bridge__pb2.BotScript.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
